app = "ai-news-bot"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[processes]
  app = "python scheduler.py"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[experimental]
  disable_http_checks = true

[deploy]
  strategy = "rolling"

# Keep machines running, no auto-stop:
[scale]
  min_machines_running = 1
  auto_stop_machines = "ignore"
